### ISSUE TITLE
ngRoute is not available

### ISSUE THREAD

**Issue by jgrannas** [kirandc/rails4_crud_with_angularjs#1]
Error: [$injector:modulerr] Failed to instantiate module ngRoute due to:
Error: [$injector:nomod] Module 'ngRoute' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.0/$injector/nomod?p0=ngRoute

What version of Angular is recommended for this?

-- Any chance you can provide hints to convert the routing in this app for ng 1.5

edit: nevermind, i noticed i forgot to add angular-route and angular-resource to my manifest...

**Comment by AjayBarot** [comment]
@jgrannas : I am using `angular-ui-router`. [`ui router`](https://github.com/angular-ui/ui-router). and its working fine. Let me know If you need help in `ngRoute` or `ui.router`. and please close the issue.

**Comment by kirandc** [comment]
@jgrannas @AjayBarot I am closing this
